# Generated by Django 4.0.3 on 2022-03-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_alter_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
