# Generated by Django 4.0.3 on 2022-03-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0006_movie_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='viewed',
            field=models.CharField(choices=[('N', 'В очереди'), ('Y', 'Просмотрено')], default='N', max_length=1),
        ),
    ]
