# Generated by Django 4.0.3 on 2022-03-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_alter_movie_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dollars'), ('RUB', 'Rubles')], default='RUB', max_length=3),
        ),
        migrations.AlterField(
            model_name='movie',
            name='viewed',
            field=models.CharField(choices=[('NO', 'В очереди'), ('YE', 'Просмотрено')], default='NO', max_length=2),
        ),
    ]
