# Generated by Django 4.0.3 on 2022-03-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0018_movie_actors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='gender',
            field=models.CharField(choices=[('FEM', 'Женщина'), ('MAL', 'Мужчина'), ('NON', 'Не известно')], default='NON', max_length=3),
        ),
    ]
