# Generated by Django 4.0.3 on 2022-03-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0022_alter_director_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default=''),
        ),
    ]
