# Generated by Django 4.0.3 on 2022-03-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0024_alter_actor_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='gender',
            field=models.CharField(choices=[('Male', 'Женщина'), ('Female', 'Мужчина'), ('No data', 'Не известно')], default='No data', max_length=15),
        ),
    ]
